version: "3.7"
services:
  python:
    build:
      dockerfile: docker/images/lambda-python/Dockerfile
      context: .
      args:
        HUID: ${HUID}
    volumes:
      - .:/usr/src/app
      - pre_commit_cache:/home/dockeruser/.cache/pre-commit
  serverless:
    build:
      dockerfile: docker/images/lambda-serverless/Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET}
  lambci:
    build:
      dockerfile: docker/images/lambci/Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
volumes:
  pre_commit_cache:
    external: false
